server:
  port:
    8762
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka/
spring:
    application:
        name:
            service-hi
    redis:
          #数据库索引
          database: 0
          host: 47.104.240.128
          port: 6379
          password:
          jedis:
            pool:
              #最大连接数
              max-active: 8
              #最大阻塞等待时间(负数表示没限制)
              max-wait: -1
              #最大空闲
              max-idle: 8
              #最小空闲
              min-idle: 0
          #连接超时时间
          timeout: 10000
    datasource:
        name: test
        url: jdbc:mysql://47.104.240.128:3306/hr
        username: root
        password: harry123123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

mybatis:
    typeAliasesPackage: com.example.demo.model