server:
  port:
    8766
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka/
spring:
    application:
        name:
            service-user
    datasource:
        url: jdbc:mysql://47.104.240.128:3306/hr?useSSL=false
        username: root
        password: harry123123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 5
        maxWait: 60000
        minIdle: 5
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        maxPoolPreparedStatementPerConnectionSize: 20

mybatis:
    typeAliasesPackage: com.example.demo.model

